bridges = []
persistence_dir = ''
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'hc-run-agent'
keystore_file = './key.key'
name = 'testAgent'
public_address = 'HcScjN8wBwrn3tuyg89aab3a69xsIgdzmX5P9537BqQZ5A7TEZu7qCY4Xzzjhma'
test_agent = true

[[dnas]]
file = '/Users/connor/code/hbe/acorn/dna-src/dist/dna-src.dna.json'
hash = 'QmXqZnZQh1uoVRu7Tj3S8xL6h1Zjcy1fnBsQRjxRAKrTqX'
id = 'hc-run-dna'

[[instances]]
agent = 'hc-run-agent'
dna = 'hc-run-dna'
id = 'test-instance'

[instances.storage]
type = 'memory'

[[interfaces]]
admin = true
id = 'websocket-interface'

[[interfaces.instances]]
id = 'test-instance'

[interfaces.driver]
port = 8888
type = 'websocket'

[logger]
state_dump = true
type = 'warn'
[[logger.rules.rules]]
exclude = true
pattern = '.*'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
dynamo_url = 'http://localhost:8000'
type = 'sim1h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
